### ISSUE TITLE
Erroneous Slack notification from Vercel deployment

### ISSUE THREAD

**Issue by ariboren** [lachlanhawthorne/lachlanhawthorne.com#1]
Hi Lachlan - posting here because I can't find any other way to reach out to you. I just received a Slack notification related to my private Next.js repository that was somehow triggered by your push to a separate repository. See screenshot below. Any idea what's going on? Could this be a Vercel/Slack bug? Email me at ari@getplayback.com - I'll delete this issue and we can try to get to the bottom of it! Thanks.

<img width="566" alt="Screen Shot 2021-01-25 at 9 51 12 AM" src="https://user-images.githubusercontent.com/3615404/105722056-40abd900-5ef3-11eb-9290-48dfcce8c995.png">

**Comment by ariboren** [comment]
Can confirm it was a bug on Vercel's end -- sorry for the alarm! Happy to forward the post-mortem email if you're interested.

**Comment by vicidroiddev** [comment]
I also received a notification on my slack channel from your repository.
